In [1]:
import numpy as np

In [6]:
list1 = [1,2,3,4,5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#generar una matríz de una forma un poco simplificada
np.arange(0,11,2) #(inicio,fin,longitud de los saltos)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(2)

array([0., 0.])

In [5]:
print(np.zeros((3,2))) #tres representa el número de filasy dos el número de columnas
print(np.ones((3,2)))
print(np.linspace(0,4,7)) #nos da una matriz de 7 valores aleatorios que comienzan del 0 y terminn en 4, en este caso, es una matriz unidimensional, un renglón

print(np.eye(4,2)) #conseguimos la matriz identidad de 4x2, si omitimos el segundo elemento, entonces Python dirá que es una matriz cuadrada de n*n
print(np.random.rand(5)) #nos da un array de 5 columnas, un renglón, números aleatorios del 0 al 1

print(np.random.randn(2))

print(np.random.randint(1,15,3)) #nos da un o más números aleatorios, teniendo la estructura (comienzo,fin(uno menos), cuantos elementos quieres)
 

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.        ]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
[0.46252622 0.77323979 0.07741914 0.18525837 0.58521959]
[-0.44804914  0.73257825]
[ 3 10  5]


In [7]:
array1 = np.arange(12)

In [8]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
array2 = np.random.randint(0,7,4)

In [10]:
array2

array([1, 0, 6, 4])

In [22]:
arr1 = array1.reshape(3,4) #convierte array1 que era unidimensional a una matriz bidimensional, hay que tener cuidado con poner el #de columnas y #de filas exactas con el total de elementos en array1

In [23]:
print(array2.reshape(2,2))

[[1 0]
 [6 4]]


In [15]:
array2.max() #esta función nos da el número más alto de nuestro array2
array1.max()

11

In [16]:
array2.min() #el número más pequeño de nuestro array2

0

In [17]:
array2.argmax() #nos da la ubicación del valor más grande que tiene array2

2

In [18]:
array2.argmin()

1

In [19]:
array2.shape #es la forma vectorial de esta, es decir, tenemos cuatro elementos en array2

(4,)

In [24]:
arr1.shape #veamos que es cierto c;

(3, 4)

In [30]:
arr1.dtype #arr1 está utlizando datos de64 bits
array2.dtype
array1.dtype

dtype('int64')

In [47]:
#indexación de arrays
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8] #debería arrojar 7, no? al indexar aquí lo que pasa el que python te "elimina" los ocho lugares del array, dicho esto, te arroja el siguiente número que es


8

In [55]:
arr[1:5] #aquí parte del primer elemento y termina en el quinto elemento

array([1, 2, 3, 4])

In [56]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[0:3] = 0
arr #sustituye los primeros tres valores con el valor que le asignemos /nota que si vuelves a correr arr en todas las casillas, ttrabja sobre este valor


array([ 0,  0,  0,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr2 = arr[1:5]
arr2[:]=1 #esta función nos cambia todos los valores de la matriz por la que le asignemos 
arr2

array([1, 1, 1, 1])

In [64]:
#copia de una matriz
#hagamos una copia de arr

copy_arr = arr.copy()
copy_arr
#ahora editemos esta copia
copy_arr[:] = 12
print(copy_arr)
print(arr)

[12 12 12 12 12 12 12 12 12 12 12]
[ 0  1  1  1  1  5  6  7  8  9 10]


In [66]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr_2d[0][1]

5

In [70]:
arr_2d[:2,1:] #estamos obteniendo una matriz apartir de arr_2d

array([[2, 3],
       [5, 6]])

In [72]:
arr_2d[:2] #da las filas 0 y 1, excepto la dos 

array([[1, 2, 3],
       [4, 5, 6]])