In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
boolean_arr = arr >5 #estamos ocupando una operación booleana
boolean_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [5]:
arr[boolean_arr]

array([6, 7, 8, 9])

In [6]:
np.sqrt(2)

1.4142135623730951

In [7]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [10]:
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
